## Accessing Elements:
#### There are several ways to access specific elements or datapoints.
#### Assume the DataFrame is defined as below:

In [3]:
import pandas as pd
import numpy as np

num = np.arange(1, 11)
pow = num**2

df = pd.DataFrame({"Number": num,
                  "Power": pow})
df.head()

   Number  Power
0       1      1
1       2      4
2       3      9
3       4     16
4       5     25

### 1) df['col']
#### To access the whole column, df[<column_name>] is used.

In [4]:
number_col = df['Number']
print(number_col)
print(type(number_col))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Number, dtype: int64
<class 'pandas.core.series.Series'>

### 2) df.column_name
#### df.<column_name> can also be used instead of df['Number'] for retrieving a single column.

In [5]:
number_col1 = df.Number
print(number_col1)
print(type(number_col1))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Number, dtype: int64
<class 'pandas.core.series.Series'>

### 3) df[['col1', 'col2']]
#### To Access multiple columns, df[['col1', 'col2', ...]]

In [6]:
number_and_power_col = df[['Number', 'Power']]
print(number_and_power_col)
print(type(number_and_power_col))

   Number  Power
0       1      1
1       2      4
2       3      9
3       4     16
4       5     25
5       6     36
6       7     49
7       8     64
8       9     81
9      10    100
<class 'pandas.core.frame.DataFrame'>

### 4) df.loc[row, col]
#### To access specific data by using the corresponding row and column.

In [7]:
third_element = df.loc[2, 'Number']
third_element

3

### 5) df.loc[row]
#### To access entire row using the index label

In [10]:
third_element = df.loc[2]
third_element

Number    3
Power     9
Name: 2, dtype: int64

### 6) df.iloc[idx]
#### To access the entire row using the row number

In [12]:
fourth_element = df.iloc[4]
fourth_element

Number     5
Power     25
Name: 4, dtype: int64

### 7) df.iloc[row, col]
#### Access one specific value by numbers.

In [19]:
fourth_element_power_column = df.iloc[3, 1]
fourth_element_power_column

16

### 8) df.at[row, col]
#### This gives the same output as df.loc[] but df.at[] is faster because it only takes the [row, col]. 
#### df.loc[] is like a general purpose accessor where loc has to determine if it is df.loc[row], df.loc[row, col], df.loc[condition], etc. This takes time.
#### Whereas, df.at[] only takes [row, col] so it can access the values faster

In [29]:
fourth_element = df.at[3, 'Power']
fourth_element

16

#### To compare the execution times of loc[] and at[], we can use 'time' module in python.
#### Only for this example, new_df is created where columns are same. Only difference is there are 1M rows instead of 10 rows as in df. This is because, the execution time difference is noticeable only when the dataset is huge.

In [47]:
import time 
import numpy as np

num = np.arange(1_000_000)
power = num ** 2

new_df = pd.DataFrame(
    {'num': num,
     'power': power}
)


# df,loc[]
start = time.perf_counter()
N = 1_000_000

for _ in range(N):
    x = new_df.loc[999999, "power"]

end = time.perf_counter()

print(f"loc: {end - start:.4f} seconds")



# df.at[]
start = time.perf_counter()

for _ in range(N):
    x = new_df.at[999999, "power"]

end = time.perf_counter()

print(f"at : {end - start:.4f} seconds")

loc: 5.1512 seconds
at : 2.3139 seconds

#### at is 2.2x faster than loc in this case. Even though the execution times are different, df.at is almost always 2x faster than df.loc

### 9) df.iat[row, col_number]
#### i stands for integer. iat[] is used to access a specific data using the index values (or integer values) of the dataframe.

In [48]:
fourth_element = df.iat[3, 1]
fourth_element

16

### 10) df.loc[start:end]
#### Splicing where index labels are used and the end is included

In [49]:
rows = df.loc[2:6]
rows

   Number  Power
2       3      9
3       4     16
4       5     25
5       6     36
6       7     49

### 11) df.iloc[start:end]
#### Splicing where the end is excluded. Integer position is used

In [50]:
rows = df.iloc[2:6]
rows

   Number  Power
2       3      9
3       4     16
4       5     25
5       6     36

### 12) df[condition]
#### Filter rows using 1 condition

In [52]:
filtered = df[df["Number"] > 4]
filtered

   Number  Power
4       5     25
5       6     36
6       7     49
7       8     64
8       9     81
9      10    100

#### The condition df[col] > 4 for example, will result in a Boolean values at each row. So, we return the rows where the Boolean value is True. This is called a Boolean Series or a Boolean Mask.

In [55]:
number_col = df["Number"] >  4

print(type(number_col))
number_col

<class 'pandas.core.series.Series'>

0    False
1    False
2    False
3    False
4     True
5     True
6     True
7     True
8     True
9     True
Name: Number, dtype: bool

### df[(condition1) & (condition2)] 
#### Multiple conditions can be used using the logical operators

In [57]:
filtered = df[(df["Number"]>4) & (df["Number"]<=8)]
filtered

   Number  Power
4       5     25
5       6     36
6       7     49
7       8     64