#### Assume the DataFrame is defined as below:

In [19]:
import pandas as pd
import numpy as np

num = np.arange(1, 11)
pow = num**2

df = pd.DataFrame({"Number": num,
                  "Power": pow})
df.head()

   Number  Power
0       1      1
1       2      4
2       3      9
3       4     16
4       5     25

### 1) df["new_column"] = values
#### Adds a new column to the DataFrame

In [20]:
df["Cube"] = df["Number"]**3
df.head()

   Number  Power  Cube
0       1      1     1
1       2      4     8
2       3      9    27
3       4     16    64
4       5     25   125

### 2) df["column"] = values
#### Modifies existing column

In [21]:
df["Power"] = df["Power"] * 10
df.head()

   Number  Power  Cube
0       1     10     1
1       2     40     8
2       3     90    27
3       4    160    64
4       5    250   125

### 3) df.insert(loc, column, values)
#### Insert a new column at a specific position

In [22]:
df.insert(1, "Fourth_Power", df["Number"]**4)

df.head()

   Number  Fourth_Power  Power  Cube
0       1             1     10     1
1       2            16     40     8
2       3            81     90    27
3       4           256    160    64
4       5           625    250   125

### 4) df.drop(labels, axis=0/1)
#### Removes specified rows and columns and returns the new DataFrame
#### axis=0 means drop the specific row
#### axis=1 means drop the whole column

In [25]:
df.head()

   Number  Fourth_Power  Power  Cube
0       1             1     10     1
1       2            16     40     8
2       3            81     90    27
3       4           256    160    64
4       5           625    250   125

In [28]:
df = df.drop("Fourth_Power", axis=1)
df.head()

   Number  Power  Cube
0       1     10     1
1       2     40     8
2       3     90    27
3       4    160    64
4       5    250   125

### 5) del df[column_name]
#### Deletes the entire column
#### It does not return a DataFrame and it cannot delete rows

In [29]:
df.head()

   Number  Power  Cube
0       1     10     1
1       2     40     8
2       3     90    27
3       4    160    64
4       5    250   125

In [ ]:
del df["Cube"]

In [32]:
df.head()

   Number  Power
0       1     10
1       2     40
2       3     90
3       4    160
4       5    250

### 6) df.sort_values()
#### Sorts the DataFrame by column values

In [35]:
df.sort_values("Power", ascending=False)

   Number  Power
9      10   1000
8       9    810
7       8    640
6       7    490
5       6    360
4       5    250
3       4    160
2       3     90
1       2     40
0       1     10