#### Assume the DataFrame is defined as below:

In [3]:
import pandas as pd
import numpy as np

num_lst = [1, 2, 3, np.nan, 5, 6, np.nan]
num = np.array(num_lst)
pow = num**2

df = pd.DataFrame({"Number": num,
                  "Power": pow})
df

   Number  Power
0     1.0    1.0
1     2.0    4.0
2     3.0    9.0
3     NaN    NaN
4     5.0   25.0
5     6.0   36.0
6     NaN    NaN

### 1) df.isna()/df.isnull()
#### Both are same and it returns a DataFrame with Boolean Values
#### It will assign True if the value is Null, else False.

In [5]:
df.isna()

   Number  Power
0   False  False
1   False  False
2   False  False
3    True   True
4   False  False
5   False  False
6    True   True

In [6]:
df.isnull()

   Number  Power
0   False  False
1   False  False
2   False  False
3    True   True
4   False  False
5   False  False
6    True   True

### 2) df.notna()/df.notnull()
#### Both are same and it returns a DataFrame with Boolean Values
#### It will assign False if the value is Null, else True.

#### It is the opposite of isna(), isnull()

In [7]:
df

   Number  Power
0     1.0    1.0
1     2.0    4.0
2     3.0    9.0
3     NaN    NaN
4     5.0   25.0
5     6.0   36.0
6     NaN    NaN

In [8]:
df.notna()

   Number  Power
0    True   True
1    True   True
2    True   True
3   False  False
4    True   True
5    True   True
6   False  False

In [9]:
df.notnull()

   Number  Power
0    True   True
1    True   True
2    True   True
3   False  False
4    True   True
5    True   True
6   False  False

### 3) df.fillna(value)
#### Fills the NAN (Not A Number) values with the specified value
#### It returns a DataFrame with the NAN values replaced with the specified value

In [10]:
df.head()

   Number  Power
0     1.0    1.0
1     2.0    4.0
2     3.0    9.0
3     NaN    NaN
4     5.0   25.0

In [13]:
df = df.fillna(0)
df.head()

   Number  Power
0     1.0    1.0
1     2.0    4.0
2     3.0    9.0
3     0.0    0.0
4     5.0   25.0

#### Using the old df

In [14]:
import pandas as pd
import numpy as np

num_lst = [1, 2, 3, np.nan, 5, 6, np.nan]
num = np.array(num_lst)
pow = num**2

df = pd.DataFrame({"Number": num,
                  "Power": pow})
df

   Number  Power
0     1.0    1.0
1     2.0    4.0
2     3.0    9.0
3     NaN    NaN
4     5.0   25.0
5     6.0   36.0
6     NaN    NaN